### ISSUE TITLE
Please consider a logging library other than glog

### ISSUE THREAD

**Issue by peterebden** [bazelbuild/remote-apis-sdks#108]
Unfortunately glog is pretty unfriendly to use in a library; when we call functions in this package we get messages printed to the console (often errors like "Logging before flag.Parse"). There doesn't seem to be any sensible way to control it (e.g. set its verbosity or configure where it outputs to) and its output is trampling over things we're trying to print at the same time.

A friendlier alternative might be google.golang.org/grpc/grpclog; it allows registering a custom logger which lets users integrate it gracefully with their chosen logging framework. Since the remote API is heavily based on grpc it's not introducing any extra dependency, although I don't know if grpc intends that to be used by anyone else or not.

I'm happy to make the code changes if we agree on what the solution should be.

**Comment by ola-rozenfeld** [comment]
Wait, it's totally supposed to do that -- you control the verbosity with the --v flag, and it shouldn't output to the console (unless --alsologtostderr is set), it outputs to the .INFO, .ERROR and .WARNING files. I think the problem is that the glog library behavior is entirely configured by command line flags -- so, yes, flag.Parse is supposed to happen first thing, otherwise it doesn't work.
Any app should basically begin by calling flag.Parse (or moreflag.Parse in our case).

**Comment by peterebden** [comment]
In our case we use a different command-line flag library - we have several needs that the stdlib one doesn't address (commands being the most obvious case). There's also the issue with not being able to redirect its output so it's printing over things we're trying to write to stderr.

On a bit more investigation though I think I can work around programmatically using CommandLine.Parse so will close this.
