### ISSUE TITLE
ActionDg shouldnot related with DoNotCache option

### ISSUE THREAD

**Issue by danni-yan** [bazelbuild/remote-apis-sdks#593]
https://github.com/bazelbuild/remote-apis-sdks/blob/e9017eaf5982ad70ac48712b57b0c2a04f0bbf10/go/pkg/rexec/rexec.go#L188

`Action` represents a repeatable action that can be performed by the execution service. So action should be defined by the command and the input. DoNotCache option is only a param for rbe system. For now if I change the DoNotCache param, the action digest will also be changed. 

I think DoNotCache option is only a tag for update cache or not. It should not be included when calc ActionDg.

**Comment by bergsieker** [comment]
The RE API declares the [do_not_cache](https://github.com/bazelbuild/remote-apis/blob/0d21f29acdb90e1b67db5873e227051af0c80cdd/build/bazel/remote/execution/v2/remote_execution.proto#L525) field as part of the Action message, so this code merely reflects that structure.

The choice to include do_not_cache in the Action is intentional. Not all actions sent to a remote execution service are necessarily hermetic and repeatable, and including the field in the Action makes it possible to correctly specify this type of Action. (Perhaps the field would have been better named as "is_hermetic" or something similar.)

**Comment by danni-yan** [comment]
Got it. I was confused by the words.

tks @bergsieker
